# Generated by Django 4.2.9 on 2024-01-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='users.patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
