# Generated by Django 4.2.9 on 2024-02-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_background_doctor_patients_doctor_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='age_category',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='alcohol_consumption',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='arthritis',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='checkup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='depression',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='diabetes',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='exercise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fried_potato_consumption',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='fruit_consumption',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='general_health',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='green_vegetable_consumption',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_disease',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_cancer',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='skin_cancer',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking_history',
            field=models.TextField(default=False),
        ),
    ]
